# Generated by Django 5.2.6 on 2025-09-14 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='Item_price',
            new_name='item_price',
        ),
    ]
