# Generated by Django 5.2.6 on 2025-09-16 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_rename_item_price_items_item_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
