# Generated by Django 5.2.6 on 2025-11-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='added_on',
            field=models.DateField(auto_now=True),
        ),
    ]
