# Generated by Django 5.2.6 on 2025-11-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_item_created_at_item_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=6),
        ),
    ]
